
version: '3'

## Setting up the network liking all containers
networks:
  private_network:
    driver: bridge
    name: private_network



services:

  ## Setting up the NGINX reverse proxy
  proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    networks:
      - private_network
    volumes:
      - ./nginx-volume/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx-proxy

  ## Setting up the Webapp-1
  webapp-1:
    image: nginx_get_started_webapp:v1.0.0
    ports:
      - "3001:3000"
    networks:
      - private_network
    environment:
      - ID="WEBAPP-1"
    container_name: webapp-1

  ## Setting up the Webapp-2
  webapp-2:
    image: nginx_get_started_webapp:v1.0.0
    ports:
      - "3002:3000"
    networks:
      - private_network
    environment:
      - ID="WEBAPP-2"
    container_name: webapp-2

  ## Setting up the Webapp-3
  webapp-3:
    image: nginx_get_started_webapp:v1.0.0
    ports:
      - "3003:3000"
    networks:
      - private_network
    environment:
      - ID="WEBAPP-3"
    container_name: webapp-3