
version: '3'

## Setting up the network liking all containers
networks:
  private_network:
    driver: bridge
    name: private_network



services:

  ## Setting up the NGINX reverse proxy
  proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    networks:
      - private_network
    container_name: nginx-proxy

  ## Setting up the Webapp-1
  webapp-1:
    build: .
    ports:
      - "3001:3000"
    networks:
      - private_network
    container_name: webapp-1

  ## Setting up the Webapp-2
  webapp-2:
    build: .
    ports:
      - "3002:3000"
    networks:
      - private_network
    container_name: webapp-2

  ## Setting up the Webapp-3
  webapp-3:
    build: .
    ports:
      - "3003:3000"
    networks:
      - private_network
    container_name: webapp-3