
version: '3'

## Setting up the network liking all containers
networks:
  private_network:
    driver: bridge
    name: private_network



services:

  ## Setting up the NGINX reverse proxy
  proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    networks:
      - private_network
    volumes:
      - ./nginx-volume/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp1
      - webapp2
      - webapp3
    container_name: nginx-proxy

  ## Setting up the Webapp-1  (only accessible inside private_network)
  webapp1:
    image: nginx_get_started_webapp:v1.0.0
    expose:
      - "3000"
    networks:
      - private_network
    environment:
      - ID="WEBAPP-1"
    container_name: webapp-1

  ## Setting up the Webapp-2 (only accessible inside private_network)
  webapp2:
    image: nginx_get_started_webapp:v1.0.0
    expose:
      - "3000"
    networks:
      - private_network
    environment:
      - ID="WEBAPP-2"
    container_name: webapp-2

  ## Setting up the Webapp-3 (only accessible inside private_network)
  webapp3:
    image: nginx_get_started_webapp:v1.0.0
    expose:
      - "3000"
    networks:
      - private_network
    environment:
      - ID="WEBAPP-3"
    container_name: webapp-3